### ISSUE TITLE
It doesn't work for a specific movie

### ISSUE THREAD

**Issue by ihor-sokoliuk** [kristal374/HDrezka-Grabber#1]
Firstly, thank you so much for the excellent extension! It helps me a lot.

Next, 
https://rezka.ag/films/action/3079-besslavnye-ublyudki-2009.html
https://rezka.ag/films/western/15-dzhango-osvobozhdennyy-2012.html

There, it doesn't allow me to download the movie. 
No option for the quality:
![image](https://github.com/kristal374/HDrezka-Grabber/assets/17313213/453279d5-c311-462d-b8b8-e5d2707eda40)

And the download button doesn't work.
I tried cleaning up the cache, browser restart, and ad blockers on/off.

My browser is Brave.

This might help:
![image](https://github.com/kristal374/HDrezka-Grabber/assets/17313213/72f5452c-858b-4ce8-b83f-41683b73c8da)
The error appeared when I inspected the extension and reloaded the movie web page.

Thank you!

**Comment by kristal374** [comment]
I have created a pre-release that you can install in developer mode. There won't be any publications on the Chrome Store soon because I am currently working on another project. However, I want to assure you that I will resume work on the extension very soon. I plan to release it on the Firefox store and also add subtitle downloads.
